# syntax=docker/dockerfile:1
FROM debian:12.0-slim AS build
LABEL Description="pymol:2.5.0 build"

ENV TZ=America/Chicago \
    DEBIAN_FRONTEND=noninteractive

WORKDIR /app
SHELL ["/bin/bash", "-c"]

RUN apt-get update && \
    apt-get -y --no-install-recommends install \
    vim libgl1 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY ./packages/2.5.0/Miniconda3-py39_4.12.0-Linux-x86_64.sh /app/
RUN cd /app/ && /bin/bash ./Miniconda3-py39_4.12.0-Linux-x86_64.sh -b -p /app/miniconda
ENV PATH=/app/miniconda/bin:${PATH}

# Install conda packages
RUN conda install -c conda-forge pymol-open-source=2.5.0
    # conda install -y -q numpy=1.20.3


FROM debian:12.0-slim AS runtime
LABEL Description="pymol:2.5.0 runtime"

ENV TZ=America/Chicago \
    DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get -y --no-install-recommends install \
    vim libgl1 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY --from=build /app/miniconda /app/miniconda
ENV PATH=/app/miniconda/bin:${PATH}

WORKDIR /mnt
